// 洗腎平台原始碼/src/components/PatientFormModal.vue
<!-- 檔案路徑: src/components/PatientFormModal.vue (✨ UI 緊湊版 ✨) -->
<template>
  <Transition name="modal-fade">
    <div v-if="isModalVisible" class="modal-overlay" v-overlay-close="closeModal">
      <div class="modal-content">
        <div class="modal-header">
          <h2>{{ isEditing ? '編輯' : '新增' }} {{ patientTypeText }}病人</h2>
          <button class="close-button" @click="closeModal" aria-label="關閉彈窗">×</button>
        </div>
        <form class="modal-body" @submit.prevent="handleSave">
          <!-- 基本資料區 (不變) -->
          <div class="form-section">
            <div class="form-grid-3-col">
              <div class="form-field">
                <label for="name">姓名</label
                ><input type="text" id="name" v-model="form.name" required />
              </div>
              <div class="form-field">
                <label for="medical-record-number">病歷號</label
                ><input
                  type="text"
                  id="medical-record-number"
                  v-model="form.medicalRecordNumber"
                  required
                />
              </div>
              <div class="form-field">
                <label>{{ patientType === 'opd' ? '收案醫師' : '會診醫師' }}</label
                ><select v-model="form.physician">
                  <option disabled value="">請選擇</option>
                  <option v-for="p in PHYSICIANS" :key="p" :value="p">{{ p }}</option>
                </select>
              </div>
              <div class="form-field">
                <label for="freq">透析頻率</label
                ><select id="freq" v-model="form.freq">
                  <option disabled value="">請選擇</option>
                  <option v-for="f in FREQ_OPTIONS" :key="f" :value="f">{{ f }}</option>
                </select>
              </div>
              <div class="form-field">
                <label for="mode">透析模式</label
                ><select id="mode" v-model="form.mode">
                  <option disabled value="">請選擇</option>
                  <option v-for="m in MODES" :key="m" :value="m">{{ m }}</option>
                </select>
              </div>
              <div class="form-field">
                <label for="status">病人狀態</label
                ><select id="status" v-model="form.status" :disabled="isEditing">
                  <option value="er">急診</option>
                  <option value="ipd">住院</option>
                  <option value="opd">門診</option>
                </select>
              </div>
              <div class="form-field">
                <label>病人身份</label>
                <div class="radio-group">
                  <label>
                    <input type="radio" v-model="form.patientCategory" value="opd_regular" />
                    <span>常規門診病人</span>
                  </label>
                  <label>
                    <input type="radio" v-model="form.patientCategory" value="non_regular" />
                    <span>非固定病人</span>
                  </label>
                </div>
              </div>
            </div>
          </div>

          <!-- ✨ 核心修正: 門診/非門診的條件渲染 -->
          <template v-if="patientType === 'opd'">
            <div class="form-section">
              <div class="opd-extra-grid">
                <div class="form-field">
                  <label for="vasc-access">目前血管通路</label
                  ><select id="vasc-access" v-model="form.vascAccess">
                    <option disabled value="">請選擇</option>
                    <option v-for="va in VASC_ACCESSES" :key="va" :value="va">{{ va }}</option>
                  </select>
                </div>
                <div class="form-field">
                  <label for="first-dialysis-date">首次透析日期</label
                  ><input type="date" id="first-dialysis-date" v-model="form.firstDialysisDate" />
                </div>
                <div class="form-field">
                  <label for="access-creation-date">通路建立日期</label
                  ><input type="date" id="access-creation-date" v-model="form.accessCreationDate" />
                </div>
                <div class="form-field">
                  <label for="hospital-info">透析院所</label>
                  <div class="hospital-input-group">
                    <input
                      type="text"
                      id="hospital-source"
                      v-model="form.hospitalInfo.source"
                      placeholder="原透析院所"
                    />
                    <div class="divider-line"></div>
                    <input
                      type="text"
                      id="hospital-transfer-out"
                      v-model="form.hospitalInfo.transferOut"
                      placeholder="轉出院所"
                    />
                  </div>
                </div>
                <div class="form-field dialysis-reason-opd">
                  <label for="dialysis-reason">透析原因</label
                  ><input type="text" id="dialysis-reason" v-model="form.dialysisReason" />
                </div>
                <div class="form-field remarks-opd">
                  <label for="remarks">備註</label
                  ><textarea id="remarks" rows="2" v-model="form.remarks"></textarea>
                </div>
              </div>
            </div>
          </template>
          <template v-else>
            <div class="form-section">
              <div class="form-field">
                <label for="hospital-info">透析院所</label>
                <div class="hospital-input-group">
                  <input
                    type="text"
                    id="hospital-source"
                    v-model="form.hospitalInfo.source"
                    placeholder="原透析院所"
                  />
                  <div class="divider-line"></div>
                  <input
                    type="text"
                    id="hospital-transfer-out"
                    v-model="form.hospitalInfo.transferOut"
                    placeholder="轉出院所"
                  />
                </div>
              </div>
            </div>
            <div class="form-section">
              <div class="form-grid-2-col">
                <div class="form-field">
                  <label for="inpatient-reason">住院原因</label
                  ><input type="text" id="inpatient-reason" v-model="form.inpatientReason" />
                </div>
                <div class="form-field">
                  <label for="dialysis-reason">透析原因</label
                  ><input type="text" id="dialysis-reason" v-model="form.dialysisReason" />
                </div>
              </div>
              <div class="form-field">
                <label for="remarks">備註</label
                ><textarea id="remarks" rows="2" v-model="form.remarks"></textarea>
              </div>
            </div>
          </template>

          <!-- 疾病與狀態標記區 (不變) -->
          <div class="form-section">
            <fieldset class="form-group">
              <legend>須注意疾病</legend>
              <div class="custom-checkbox-container">
                <div
                  v-for="d in DISEASES"
                  :key="d"
                  class="custom-checkbox"
                  :class="{
                    selected: form.diseases?.includes(d),
                    [`disease-${d.toLowerCase()}`]: form.diseases?.includes(d),
                  }"
                  @click="toggleDisease(d)"
                >
                  {{ d }}
                </div>
              </div>
            </fieldset>
            <fieldset v-if="form.patientStatus" class="form-group">
              <legend>狀態標記</legend>
              <div class="custom-checkbox-container">
                <div
                  class="status-date-tag"
                  :class="{ active: form.patientStatus.isFirstDialysis.active }"
                  @click="toggleStatus('isFirstDialysis')"
                >
                  <span>首透</span
                  ><input
                    v-if="form.patientStatus.isFirstDialysis.active"
                    type="date"
                    v-model="form.patientStatus.isFirstDialysis.date"
                    @click.stop
                  />
                </div>
                <div
                  class="status-date-tag"
                  :class="{ active: form.patientStatus.isPaused.active }"
                  @click="toggleStatus('isPaused')"
                >
                  <span>暫停透析</span
                  ><input
                    v-if="form.patientStatus.isPaused.active"
                    type="date"
                    v-model="form.patientStatus.isPaused.date"
                    @click.stop
                  />
                </div>
                <div
                  v-if="patientType !== 'opd'"
                  class="status-date-tag"
                  :class="{ active: form.patientStatus.hasBloodDraw.active }"
                  @click="toggleStatus('hasBloodDraw')"
                >
                  <span>已抽血</span
                  ><input
                    v-if="form.patientStatus.hasBloodDraw.active"
                    type="date"
                    v-model="form.patientStatus.hasBloodDraw.date"
                    @click.stop
                  />
                </div>
              </div>
            </fieldset>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn-secondary" @click="closeModal">取消</button
            ><button type="submit" class="btn-primary">儲存</button>
          </div>
        </form>
      </div>
    </div>
  </Transition>
</template>

<script setup>
import { ref, watch, computed } from 'vue'
const props = defineProps({
  isModalVisible: { type: Boolean, required: true },
  patientData: { type: Object, default: () => ({}) },
  patientType: { type: String, required: true },
})
const emit = defineEmits(['close', 'save'])
const form = ref({})
const PHYSICIANS = ['廖丁瑩', '蔡宜潔', '蘇哲弘', '蔡亨政', '陳怡汝']
const FREQ_OPTIONS = [
  '一三五',
  '二四六',
  '一四',
  '二五',
  '三六',
  '一五', // <-- 新增
  '二六', // <-- 新增
  '每日',
  '每周一',
  '每周二',
  '每周三',
  '每周四',
  '每周五',
  '每周六',
  '臨時',
]
const MODES = ['HD', 'SLED', 'CVVHDF', 'PP', 'DFPP', 'Lipid']
const VASC_ACCESSES = ['Double lumen', 'PERM', '左手AVF', '右手AVF', '左手AVG', '右手AVG']
const DISEASES = ['HIV', 'RPR', 'BC肝?', 'HBV', 'HCV', 'C肝治癒', 'COVID', '隔離']
const isEditing = computed(() => !!(form.value && form.value.id))
const patientTypeText = computed(() => {
  const map = { ipd: '住院', opd: '門診', er: '急診' }
  return map[props.patientType] || ''
})

function toggleDisease(disease) {
  const index = (form.value.diseases || []).indexOf(disease)
  if (index > -1) {
    form.value.diseases.splice(index, 1)
  } else {
    form.value.diseases.push(disease)
  }
}
function toggleStatus(key) {
  if (form.value.patientStatus && form.value.patientStatus[key]) {
    const status = form.value.patientStatus[key]
    status.active = !status.active
    if (!status.active) {
      status.date = null
    }
  }
}
function closeModal() {
  emit('close')
}
function handleSave() {
  if (!form.value.name || !form.value.medicalRecordNumber) {
    alert('姓名和病歷號為必填項！')
    return
  }
  emit('save', form.value)
}

watch(
  () => props.isModalVisible,
  (isVisible) => {
    if (isVisible) {
      document.body.classList.add('modal-open')
      const data = JSON.parse(JSON.stringify(props.patientData))

      if (!data.id) {
        // 只在「新增」病人時觸發
        data.status = props.patientType
        // ✅ [修正] 根據 patientType 設定不同的預設病人身份
        if (props.patientType === 'opd') {
          data.patientCategory = 'opd_regular' // 從門診新增，預設為「常規」
        } else {
          data.patientCategory = 'non_regular' // 從住院或急診新增，預設為「非固定」
        }
      }

      // 當「編輯」既有病人時，如果該病人沒有 patientCategory 欄位，給予一個預設值
      if (!data.patientCategory) {
        data.patientCategory = 'opd_regular'
      }

      // ✅ [修正] 確保 patientStatus 和其子屬性都有正確的預設值
      data.diseases = data.diseases || []
      const defaultPatientStatus = {
        isFirstDialysis: { active: false, date: null },
        isPaused: { active: false, date: null },
        hasBloodDraw: { active: false, date: null },
      }
      // 深度合併，確保即使 patientStatus 是空物件，子屬性也會被初始化
      data.patientStatus = {
        isFirstDialysis: { ...defaultPatientStatus.isFirstDialysis, ...(data.patientStatus?.isFirstDialysis || {}) },
        isPaused: { ...defaultPatientStatus.isPaused, ...(data.patientStatus?.isPaused || {}) },
        hasBloodDraw: { ...defaultPatientStatus.hasBloodDraw, ...(data.patientStatus?.hasBloodDraw || {}) },
      }
      data.hospitalInfo = data.hospitalInfo || { source: '', transferOut: '' }

      form.value = data
    } else {
      document.body.classList.remove('modal-open')
    }
  },
)
</script>

<style scoped>
:global(body.modal-open) {
  overflow: hidden;
}
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.6);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}
.modal-content {
  background-color: #fff;
  padding: 1.5rem;
  border: 1px solid #dee2e6;
  width: 90%;
  max-width: 900px;
  border-radius: 12px;
  box-shadow: 0 8px 25px rgba(0, 0, 0, 0.15);
  display: flex;
  flex-direction: column;
  max-height: 90vh;
}
.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid #e9ecef;
  padding-bottom: 1rem;
  margin-bottom: 0;
  flex-shrink: 0;
}
.modal-header h2 {
  margin: 0;
  font-size: 1.5rem;
  font-weight: 600;
}
.close-button {
  background: none;
  border: none;
  font-size: 2rem;
  line-height: 1;
  color: #adb5bd;
  cursor: pointer;
  padding: 0;
  transition: color 0.2s;
}
.close-button:hover {
  color: #495057;
}
.modal-body {
  overflow-y: auto;
  padding: 0.5rem 1.5rem 0.5rem 0;
  margin-right: -1.5rem;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}
.form-field {
  display: flex;
  flex-direction: column;
}
.form-field label {
  margin-bottom: 6px;
  font-weight: 500;
  color: #495057;
  font-size: 0.9rem;
}
.form-field input[type='text'],
.form-field input[type='date'],
.form-field select,
.form-field textarea {
  padding: 8px 12px;
  border: 1px solid #ced4da;
  border-radius: 6px;
  width: 100%;
  box-sizing: border-box;
  font-size: 1rem;
  transition:
    border-color 0.2s,
    box-shadow 0.2s;
}
.form-field input:focus,
.form-field select:focus,
.form-field textarea:focus {
  outline: none;
  border-color: var(--primary-color, #007bff);
  box-shadow: 0 0 0 3px rgba(0, 123, 255, 0.2);
}
.form-group {
  border: none;
  padding: 0;
  margin: 0;
}
.form-group legend {
  padding: 0 8px;
  font-weight: 500;
  color: #495057;
  font-size: 0.95rem;
  margin-bottom: 10px;
  margin-left: -8px;
}
.custom-checkbox-container {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}
.custom-checkbox {
  padding: 6px 14px;
  border: 1px solid #ced4da;
  border-radius: 20px;
  cursor: pointer;
  -webkit-user-select: none;
  user-select: none;
  transition: all 0.2s ease-in-out;
  font-weight: 500;
  color: #495057;
  background-color: #fff;
  font-size: 0.9rem;
}
.custom-checkbox:hover {
  border-color: #adb5bd;
  background-color: #f8f9fa;
}
.custom-checkbox.selected {
  color: #fff;
  border-color: transparent;
  background-color: var(--primary-color, #007bff);
}
.custom-checkbox.selected.disease-bc肝\? {
  background-color: var(--danger-color, #dc3545);
}
.custom-checkbox.selected.disease-covid,
.custom-checkbox.selected.disease-hbv,
.custom-checkbox.selected.disease-hcv,
.custom-checkbox.selected.disease-hiv,
.custom-checkbox.selected.disease-rpr {
  background-color: var(--danger-color, #dc3545);
}
.custom-checkbox.selected.disease-隔離 {
  background-color: var(--warning-color, #ffc107);
  color: #212529;
}
.modal-footer {
  margin-top: auto;
  padding-top: 1rem;
  border-top: 1px solid #e9ecef;
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  flex-shrink: 0;
}
.modal-footer button {
  padding: 10px 24px;
  font-size: 1rem;
  font-weight: 500;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  transition: background-color 0.2s;
}
.btn-primary {
  background-color: var(--primary-color, #007bff);
  color: #fff;
}
.btn-primary:hover {
  background-color: #0056b3;
}
.btn-secondary {
  background-color: #f8f9fa;
  color: #343a40;
  border: 1px solid #ced4da;
}
.btn-secondary:hover {
  background-color: #e9ecef;
}
.modal-fade-enter-active,
.modal-fade-leave-active {
  transition: opacity 0.3s ease;
}
.modal-fade-enter-from,
.modal-fade-leave-to {
  opacity: 0;
}
.modal-fade-enter-active .modal-content,
.modal-fade-leave-active .modal-content {
  transition: transform 0.3s ease;
}
.modal-fade-enter-from .modal-content,
.modal-fade-leave-to .modal-content {
  transform: translateY(-20px);
}
.hospital-input-group {
  display: flex;
  align-items: center;
  border: 1px solid #ced4da;
  border-radius: 6px;
  overflow: hidden;
  transition:
    border-color 0.2s,
    box-shadow 0.2s;
}
.hospital-input-group:focus-within {
  border-color: var(--primary-color, #007bff);
  box-shadow: 0 0 0 3px rgba(0, 123, 255, 0.2);
}
.hospital-input-group input {
  border: none;
  flex: 1;
  min-width: 0;
}
.hospital-input-group input:focus {
  outline: none;
  box-shadow: none;
}
.divider-line {
  width: 1px;
  background-color: #ced4da;
  align-self: stretch;
  margin: 4px 0;
}
.status-date-tag {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 6px 12px;
  border: 1px solid #ced4da;
  border-radius: 20px;
  cursor: pointer;
  -webkit-user-select: none;
  user-select: none;
  transition: all 0.2s ease-in-out;
  font-weight: 500;
  color: #495057;
  background-color: #fff;
  font-size: 0.9rem;
}
.status-date-tag:hover {
  border-color: #adb5bd;
  background-color: #f8f9fa;
}
.status-date-tag.active {
  color: #fff;
  border-color: var(--primary-color, #007bff);
  background-color: var(--primary-color, #007bff);
}
.status-date-tag input[type='date'] {
  background-color: transparent;
  border: none;
  color: #fff;
  padding: 0;
  font-size: 0.9em;
  width: 140px;
}
.status-date-tag.active input[type='date']::-webkit-calendar-picker-indicator {
  filter: invert(1);
}

.form-section {
  padding: 1rem;
  border-radius: 8px;
  background-color: #f8f9fa;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}
.form-section:nth-child(odd) {
  background-color: #ffffff;
}
.form-grid-3-col {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1rem 1.25rem;
}
.form-grid-2-col {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem 1.25rem;
}

/* ✨ 核心修正: 門診專用網格佈局 */
.opd-extra-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr); /* 預設三欄 */
  gap: 1rem 1.25rem;
}
.dialysis-reason-opd {
  grid-column: span 2; /* 透析原因佔兩欄 */
}
.remarks-opd {
  grid-column: 1 / -1; /* 備註佔滿整行 */
}

.radio-group {
  display: flex;
  gap: 1.5rem;
  padding: 8px 0;
}
.radio-group label {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-weight: normal; /* 覆蓋 form-field label 的粗體 */
  cursor: pointer;
}
.radio-group input[type='radio'] {
  width: auto;
  accent-color: var(--primary-color, #007bff);
}

/* 在螢幕寬度小於 700px 時，變回單欄，避免擁擠 */
@media (max-width: 700px) {
  .opd-extra-grid {
    grid-template-columns: 1fr;
  }
  .dialysis-reason-opd {
    grid-column: auto;
  }
}
</style>

// angular-client/src/app/components/dialogs/patient-form-modal/patient-form-modal.component.ts
import { Component, Input, Output, EventEmitter, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiManagerService, type ApiManager, type FirestoreRecord } from '@app/core/services/api-manager.service';
import { addDaysToDateString, getTaipeiWeekdayIndex, getToday } from '@/utils/dateUtils';

@Component({
  selector: 'app-patient-form-modal',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './patient-form-modal.component.html',
  styleUrl: './patient-form-modal.component.css'
})
export class PatientFormModalComponent implements OnInit {
  private readonly apiManager = inject(ApiManagerService);
  private readonly baseSchedulesApi: ApiManager<FirestoreRecord>;
  private readonly schedulesApi: ApiManager<FirestoreRecord>;

  @Input() patientData: any = {};
  @Input() patientType = '';
  @Output() close = new EventEmitter<void>();
  @Output() save = new EventEmitter<any>();

  form: any = {};
  isFirstPlanVisible = false;
  firstPlanLoading = false;
  firstPlanError = '';
  masterRules: Record<string, any> = {};
  dailySchedules: Record<string, Record<string, any>> = {};
  firstPlan: any = {
    startDate: '',
    continuousDays: 3,
    regularFreq: '',
    regularAssignment: null,
    selectedExtraDate: '',
    extraSessions: [],
  };

  readonly PHYSICIANS = ['廖丁瑩', '蔡宜潔', '蘇哲弘', '蔡亨政'];
  readonly FREQ_OPTIONS = [
    '一三五', '二四六', '一四', '二五', '三六',
    '一五', '二六', '每日',
    '每周一', '每周二', '每周三', '每周四', '每周五', '每周六',
    '臨時',
  ];
  readonly MODES = ['HD', 'SLED', 'CVVHDF', 'PP', 'DFPP', 'Lipid'];
  readonly SHIFTS = ['early', 'noon', 'late'];
  readonly SHIFT_LABELS: Record<string, string> = { early: '早班', noon: '午班', late: '晚班' };
  readonly WEEKDAY_LABELS = ['一', '二', '三', '四', '五', '六'];
  readonly HEPATITIS_BEDS = [31, 32, 33, 35, 36];
  readonly BED_LAYOUT: (number | string)[] = [
    1, 2, 3, 5, 6, 7, 8, 9, 11, 12, 13, 15, 16, 17, 18, 19,
    21, 22, 23, 25, 26, 27, 28, 29, 31, 32, 33, 35, 36, 37, 38, 39,
    51, 52, 53, 55, 56, 57, 58, 59, 61, 62, 63, 65,
    ...Array.from({ length: 6 }, (_, i) => `peripheral-${i + 1}`),
  ];
  readonly FREQ_MAP_TO_DAY_INDEX: Record<string, number[]> = {
    '一三五': [0, 2, 4],
    '二四六': [1, 3, 5],
    '一四': [0, 3],
    '二五': [1, 4],
    '三六': [2, 5],
    '一五': [0, 4],
    '二六': [1, 5],
    '每日': [0, 1, 2, 3, 4, 5],
    '每周一': [0],
    '每周二': [1],
    '每周三': [2],
    '每周四': [3],
    '每周五': [4],
    '每周六': [5],
  };
  readonly VASC_ACCESSES = ['Double lumen', 'PERM', '左臂AVF', '右臂AVF', '左臂AVG', '右臂AVG'];
  readonly DISEASES = ['HIV', 'RPR', 'BC肝?', 'HBV', 'HCV', 'C肝治癒', 'COVID', '隔離'];

  constructor() {
    this.baseSchedulesApi = this.apiManager.create<FirestoreRecord>('base_schedules');
    this.schedulesApi = this.apiManager.create<FirestoreRecord>('schedules');
  }

  get isEditing(): boolean {
    return !!(this.form && this.form.id);
  }

  get patientTypeText(): string {
    const map: Record<string, string> = { ipd: '住院', opd: '門診', er: '急診' };
    return map[this.patientType] || '';
  }

  ngOnInit(): void {
    document.body.classList.add('modal-open');
    const data = JSON.parse(JSON.stringify(this.patientData || {}));
    if (!data.id) {
      data.status = this.patientType;
      data.patientCategory = this.patientType === 'opd' ? 'opd_regular' : 'non_regular';
    }
    if (!data.patientCategory) data.patientCategory = 'opd_regular';
    data.diseases = data.diseases || [];
    data.patientStatus = data.patientStatus || {
      isFirstDialysis: { active: false, date: null },
      isPaused: { active: false, date: null },
      hasBloodDraw: { active: false, date: null },
    };
    data.hospitalInfo = data.hospitalInfo || { source: '', transferOut: '' };
    this.form = data;
    this.ensurePatientStatus();
    this.syncFirstDialysisStatus(this.form.firstDialysisDate);
  }

  toggleDisease(disease: string): void {
    const index = (this.form.diseases || []).indexOf(disease);
    if (index > -1) {
      this.form.diseases.splice(index, 1);
    } else {
      this.form.diseases.push(disease);
    }
  }

  isDiseaseSelected(disease: string): boolean {
    return (this.form.diseases || []).includes(disease);
  }

  toggleStatus(key: string): void {
    if (this.form.patientStatus && this.form.patientStatus[key]) {
      const status = this.form.patientStatus[key];
      status.active = !status.active;
      if (key === 'isFirstDialysis' && status.active && !status.date && this.form.firstDialysisDate) {
        status.date = this.form.firstDialysisDate;
      }
      if (!status.active) status.date = null;
    }
  }

  handleFirstDialysisDateChange(date: string | null): void {
    this.syncFirstDialysisStatus(date, true);
  }

  private ensurePatientStatus(): void {
    this.form.patientStatus = this.form.patientStatus || {};
    this.form.patientStatus.isFirstDialysis = this.form.patientStatus.isFirstDialysis || { active: false, date: null };
    this.form.patientStatus.isPaused = this.form.patientStatus.isPaused || { active: false, date: null };
    this.form.patientStatus.hasBloodDraw = this.form.patientStatus.hasBloodDraw || { active: false, date: null };
    this.form.patientStatus.doNotMove = this.form.patientStatus.doNotMove || { active: false, reason: '' };
  }

  /** 切換「勿動」鎖定；關閉時清除原因 */
  toggleDoNotMove(): void {
    this.ensurePatientStatus();
    const status = this.form.patientStatus.doNotMove;
    status.active = !status.active;
    if (!status.active) status.reason = '';
  }

  private syncFirstDialysisStatus(date: string | null | undefined, forceDate = false): void {
    this.ensurePatientStatus();
    const status = this.form.patientStatus.isFirstDialysis;
    if (date) {
      status.active = true;
      if (forceDate || !status.date) status.date = date;
    } else if (forceDate && status.active) {
      status.date = null;
    }
  }

  async openFirstDialysisPlan(): Promise<void> {
    const previousPlan = this.form.firstDialysisPlan || this.form.dialysisOrders?.firstDialysisPlan || null;
    const previousRegularRule = previousPlan?.regularRule || null;
    const previousShiftCode = previousRegularRule?.shiftCode
      || (Number.isInteger(previousRegularRule?.shiftIndex) ? this.SHIFTS[previousRegularRule.shiftIndex] : null);
    const previousRegularAssignment = previousRegularRule?.bedNum && previousShiftCode
      ? { bedNum: previousRegularRule.bedNum, shiftCode: previousShiftCode }
      : null;
    const previousExtraSessions = Array.isArray(previousPlan?.extraSessions)
      ? previousPlan.extraSessions.map((item: any) => ({
          date: item.date,
          bedNum: item.bedNum,
          shiftCode: item.shiftCode,
          reason: item.reason || '首透連續洗臨時加洗',
        }))
      : [];

    this.firstPlan = {
      startDate: previousPlan?.startDate || this.form.firstDialysisDate || getToday(),
      continuousDays: previousPlan?.continuousDays || 3,
      regularFreq: previousRegularRule?.freq || this.form.freq || '一三五',
      regularAssignment: previousRegularAssignment,
      selectedExtraDate: previousExtraSessions[0]?.date || '',
      extraSessions: previousExtraSessions,
    };
    this.firstPlanError = '';
    this.isFirstPlanVisible = true;
    await this.loadMasterRules();
    if (this.firstPlan.selectedExtraDate) {
      await this.loadDailyScheduleForFirstPlanDate(this.firstPlan.selectedExtraDate);
    }
  }

  async loadMasterRules(): Promise<void> {
    this.firstPlanLoading = true;
    try {
      const master = await this.baseSchedulesApi.fetchById('MASTER_SCHEDULE');
      this.masterRules = (master?.['schedule'] as Record<string, any>) || {};
    } catch (error: any) {
      this.firstPlanError = `無法載入床位總表：${error.message || error}`;
    } finally {
      this.firstPlanLoading = false;
    }
  }

  closeFirstDialysisPlan(): void {
    this.isFirstPlanVisible = false;
  }

  private async loadDailyScheduleForFirstPlanDate(date: string): Promise<void> {
    if (!date || this.dailySchedules[date]) return;
    this.firstPlanLoading = true;
    try {
      const daySchedule = await this.schedulesApi.fetchById(date);
      this.dailySchedules[date] = (daySchedule?.['schedule'] as Record<string, any>) || {};
    } catch {
      this.dailySchedules[date] = {};
    } finally {
      this.firstPlanLoading = false;
    }
  }

  private getFreqDays(freq: string | undefined | null): number[] {
    if (!freq) return [];
    const direct = this.FREQ_MAP_TO_DAY_INDEX[freq];
    if (direct) return direct;
    const daysByOptionIndex = [
      [0, 2, 4], [1, 3, 5], [0, 3], [1, 4], [2, 5],
      [0, 4], [1, 5], [0, 1, 2, 3, 4, 5],
      [0], [1], [2], [3], [4], [5],
    ];
    const index = this.FREQ_OPTIONS.indexOf(freq);
    return daysByOptionIndex[index] || [];
  }

  private isRegularFirstPlanDate(dateStr: string): boolean {
    if (!dateStr) return false;
    const weekdayIndex = getTaipeiWeekdayIndex(dateStr);
    return this.getFreqDays(this.firstPlan.regularFreq).includes(weekdayIndex);
  }

  get regularAvailableBeds(): Record<string, (number | string)[]> {
    const result: Record<string, (number | string)[]> = { early: [], noon: [], late: [] };
    const days = this.getFreqDays(this.firstPlan.regularFreq);
    if (days.length === 0) return result;
    this.BED_LAYOUT.forEach((bedNum) => {
      this.SHIFTS.forEach((shiftCode, shiftIndex) => {
        const conflict = Object.entries(this.masterRules || {}).some(([patientId, rule]: [string, any]) => {
          if (patientId === this.form.id) return false;
          if (String(rule?.bedNum) !== String(bedNum)) return false;
          if (Number(rule?.shiftIndex) !== shiftIndex) return false;
          const otherDays = this.getFreqDays(rule?.freq);
          return days.some((day) => otherDays.includes(day));
        });
        if (!conflict) result[shiftCode].push(bedNum);
      });
    });
    return result;
  }

  get continuousDates(): any[] {
    if (!this.firstPlan.startDate) return [];
    const count = Math.max(1, Math.min(Number(this.firstPlan.continuousDays) || 3, 6));
    return Array.from({ length: count }, (_, index) => {
      const date = addDaysToDateString(this.firstPlan.startDate, index);
      const weekdayIndex = getTaipeiWeekdayIndex(date);
      return {
        date,
        weekdayIndex,
        weekdayLabel: weekdayIndex >= 0 ? this.WEEKDAY_LABELS[weekdayIndex] : '日',
        isRegular: this.getFreqDays(this.firstPlan.regularFreq).includes(weekdayIndex),
      };
    }).filter((item) => item.weekdayIndex >= 0 && item.weekdayIndex < 6);
  }

  get selectedExtraSession(): any {
    return this.firstPlan.extraSessions.find((item: any) => item.date === this.firstPlan.selectedExtraDate) || null;
  }

  async selectExtraDate(date: string): Promise<void> {
    const dateInfo = this.continuousDates.find((item) => item.date === date);
    if (!dateInfo || dateInfo.isRegular || this.isRegularFirstPlanDate(date)) return;
    this.firstPlan.selectedExtraDate = date;
    await this.loadDailyScheduleForFirstPlanDate(date);
    if (!this.selectedExtraSession) {
      this.firstPlan.extraSessions.push({ date, bedNum: null, shiftCode: null });
    }
  }

  get extraAvailableBeds(): Record<string, (number | string)[]> {
    const result: Record<string, (number | string)[]> = { early: [], noon: [], late: [] };
    const date = this.firstPlan.selectedExtraDate;
    if (!date) return result;
    const schedule = this.dailySchedules[date] || {};
    this.BED_LAYOUT.forEach((bedNum) => {
      this.SHIFTS.forEach((shiftCode) => {
        const slotKey = this.getDailySlotKey(bedNum, shiftCode);
        const occupant = schedule[slotKey];
        if (!occupant?.patientId || occupant.patientId === this.form.id) result[shiftCode].push(bedNum);
      });
    });
    return result;
  }

  selectRegularBed(bedNum: number | string, shiftCode: string): void {
    this.firstPlan.regularAssignment = { bedNum, shiftCode };
  }

  selectExtraBed(bedNum: number | string, shiftCode: string): void {
    const session = this.selectedExtraSession;
    if (!session) return;
    session.bedNum = bedNum;
    session.shiftCode = shiftCode;
  }

  removeExtraSession(date: string, event?: Event): void {
    event?.stopPropagation();
    this.firstPlan.extraSessions = this.firstPlan.extraSessions.filter((item: any) => item.date !== date);
    if (this.firstPlan.selectedExtraDate === date) this.firstPlan.selectedExtraDate = '';
  }

  applyFirstDialysisPlan(): void {
    if (!this.firstPlan.regularFreq || !this.firstPlan.regularAssignment) {
      this.firstPlanError = '請選擇常規頻率與常規床位。';
      return;
    }
    const validExtraDates = new Set(this.continuousDates.filter((item) => !item.isRegular).map((item) => item.date));
    const extraSessions = this.firstPlan.extraSessions.filter((item: any) => validExtraDates.has(item.date));
    if (extraSessions.some((item: any) => !item.bedNum || !item.shiftCode)) {
      this.firstPlanError = '請完成每個加洗日的床位選擇，或移除不需要的加洗日。';
      return;
    }
    this.form.freq = this.firstPlan.regularFreq;
    this.form.firstDialysisDate = this.firstPlan.startDate;
    this.syncFirstDialysisStatus(this.firstPlan.startDate, true);
    this.form.firstDialysisPlan = {
      startDate: this.firstPlan.startDate,
      continuousDays: this.firstPlan.continuousDays,
      regularRule: {
        freq: this.firstPlan.regularFreq,
        ...this.firstPlan.regularAssignment,
      },
      extraSessions: extraSessions.map((item: any) => ({
        date: item.date,
        bedNum: item.bedNum,
        shiftCode: item.shiftCode,
        reason: '首透連續洗臨時加洗',
      })),
    };
    this.isFirstPlanVisible = false;
  }

  hasExtraSession(date: string): boolean {
    return this.firstPlan.extraSessions.some((item: any) => item.date === date);
  }

  isHepatitisBed(bedNum: number | string): boolean {
    return typeof bedNum === 'number' && this.HEPATITIS_BEDS.includes(bedNum);
  }

  getDailySlotKey(bedNum: number | string, shiftCode: string): string {
    return typeof bedNum === 'string' && bedNum.startsWith('peripheral-')
      ? `${bedNum}-${shiftCode}`
      : `bed-${bedNum}-${shiftCode}`;
  }

  formatBed(bedNum: number | string): string {
    return typeof bedNum === 'string' ? `外圍 ${String(bedNum).replace('peripheral-', '')}` : `${bedNum}床`;
  }

  formatAssignment(assignment: any): string {
    if (!assignment?.bedNum || !assignment?.shiftCode) return '未選擇';
    return `${this.formatBed(assignment.bedNum)} ${this.SHIFT_LABELS[assignment.shiftCode] || assignment.shiftCode}`;
  }

  formatExtraSessionsSummary(sessions: any[] = []): string {
    const validSessions = (sessions || []).filter((item) => item?.date);
    if (validSessions.length === 0) return '無';
    return validSessions
      .map((item) => `${item.date} ${this.formatAssignment(item)}`)
      .join('、');
  }

  closeModal(): void {
    document.body.classList.remove('modal-open');
    this.close.emit();
  }

  handleSave(): void {
    if (!this.form.name || !this.form.medicalRecordNumber) {
      alert('姓名和病歷號為必填項！');
      return;
    }
    this.save.emit(this.form);
  }
}

<div class="modal-overlay" (click)="closeModal()">
  <div class="modal-content" (click)="$event.stopPropagation()">
    <div class="modal-header">
      <h2>{{ isEditing ? '編輯' : '新增' }} {{ patientTypeText }}病人</h2>
      <button class="close-button" (click)="closeModal()" aria-label="關閉彈窗">&times;</button>
    </div>
    <form class="modal-body" (ngSubmit)="handleSave()">
      <div class="form-section">
        <div class="form-grid-3-col">
          <div class="form-field">
            <label for="name">姓名</label>
            <input type="text" id="name" [(ngModel)]="form.name" name="name" required />
          </div>
          <div class="form-field">
            <label for="medical-record-number">病歷號</label>
            <input type="text" id="medical-record-number" [(ngModel)]="form.medicalRecordNumber" name="mrn" required />
          </div>
          <div class="form-field">
            <label>{{ patientType === 'opd' ? '收案醫師' : '會診醫師' }}</label>
            <select [(ngModel)]="form.physician" name="physician">
              <option disabled value="">請選擇</option>
              @for (p of PHYSICIANS; track p) {
                <option [value]="p">{{ p }}</option>
              }
            </select>
          </div>
          <div class="form-field">
            <label for="freq">透析頻率</label>
            <div class="freq-with-action">
            <select id="freq" [(ngModel)]="form.freq" name="freq">
              <option disabled value="">請選擇</option>
              @for (f of FREQ_OPTIONS; track f) {
                <option [value]="f">{{ f }}</option>
              }
            </select>
            <button type="button" class="btn-inline" (click)="openFirstDialysisPlan()">首透連續洗</button>
            </div>
            @if (form.firstDialysisPlan) {
              <small class="plan-summary">
                常規 {{ form.firstDialysisPlan.regularRule?.freq }} / {{ formatAssignment(form.firstDialysisPlan.regularRule) }}，
                加洗 {{ formatExtraSessionsSummary(form.firstDialysisPlan.extraSessions) }}
              </small>
            }
          </div>
          <div class="form-field">
            <label for="mode">透析模式</label>
            <select id="mode" [(ngModel)]="form.mode" name="mode">
              <option disabled value="">請選擇</option>
              @for (m of MODES; track m) {
                <option [value]="m">{{ m }}</option>
              }
            </select>
          </div>
          <div class="form-field">
            <label for="status">病人狀態</label>
            <select id="status" [(ngModel)]="form.status" name="status" [disabled]="isEditing">
              <option value="er">急診</option>
              <option value="ipd">住院</option>
              <option value="opd">門診</option>
            </select>
          </div>
          <div class="form-field">
            <label>病人身份</label>
            <div class="radio-group">
              <label><input type="radio" [(ngModel)]="form.patientCategory" name="patientCategory" value="opd_regular" /><span>常規門診病人</span></label>
              <label><input type="radio" [(ngModel)]="form.patientCategory" name="patientCategory" value="non_regular" /><span>非固定病人</span></label>
            </div>
          </div>
        </div>
      </div>

      @if (patientType === 'opd') {
        <div class="form-section">
          <div class="opd-extra-grid">
            <div class="form-field">
              <label for="vasc-access">目前血管通路</label>
              <select id="vasc-access" [(ngModel)]="form.vascAccess" name="vascAccess">
                <option disabled value="">請選擇</option>
                @for (va of VASC_ACCESSES; track va) {
                  <option [value]="va">{{ va }}</option>
                }
              </select>
            </div>
            <div class="form-field">
              <label for="first-dialysis-date">首次透析日期</label>
              <input type="date" id="first-dialysis-date" [(ngModel)]="form.firstDialysisDate" name="firstDialysisDate" (ngModelChange)="handleFirstDialysisDateChange($event)" />
            </div>
            <div class="form-field">
              <label for="access-creation-date">通路建立日期</label>
              <input type="date" id="access-creation-date" [(ngModel)]="form.accessCreationDate" name="accessCreationDate" />
            </div>
            <div class="form-field">
              <label>透析院所</label>
              <div class="hospital-input-group">
                <input type="text" [(ngModel)]="form.hospitalInfo.source" name="hospitalSource" placeholder="原透析院所" />
                <div class="divider-line"></div>
                <input type="text" [(ngModel)]="form.hospitalInfo.transferOut" name="hospitalTransferOut" placeholder="轉出院所" />
              </div>
            </div>
            <div class="form-field dialysis-reason-opd">
              <label for="dialysis-reason">透析原因</label>
              <input type="text" id="dialysis-reason" [(ngModel)]="form.dialysisReason" name="dialysisReason" />
            </div>
            <div class="form-field remarks-opd">
              <label for="remarks">備註</label>
              <textarea id="remarks" rows="2" [(ngModel)]="form.remarks" name="remarks"></textarea>
            </div>
          </div>
        </div>
      } @else {
        <div class="form-section">
          <div class="form-field">
            <label>透析院所</label>
            <div class="hospital-input-group">
              <input type="text" [(ngModel)]="form.hospitalInfo.source" name="hospitalSource" placeholder="原透析院所" />
              <div class="divider-line"></div>
              <input type="text" [(ngModel)]="form.hospitalInfo.transferOut" name="hospitalTransferOut" placeholder="轉出院所" />
            </div>
          </div>
        </div>
        <div class="form-section">
          <div class="form-grid-2-col">
            <div class="form-field">
              <label for="inpatient-reason">住院原因</label>
              <input type="text" id="inpatient-reason" [(ngModel)]="form.inpatientReason" name="inpatientReason" />
            </div>
            <div class="form-field">
              <label for="dialysis-reason">透析原因</label>
              <input type="text" id="dialysis-reason" [(ngModel)]="form.dialysisReason" name="dialysisReason" />
            </div>
          </div>
          <div class="form-field">
            <label for="remarks">備註</label>
            <textarea id="remarks" rows="2" [(ngModel)]="form.remarks" name="remarks"></textarea>
          </div>
        </div>
      }

      <div class="form-section">
        <fieldset class="form-group">
          <legend>須注意疾病</legend>
          <div class="custom-checkbox-container">
            @for (d of DISEASES; track d) {
              <div class="custom-checkbox" [class.selected]="isDiseaseSelected(d)" (click)="toggleDisease(d)">
                {{ d }}
              </div>
            }
          </div>
        </fieldset>
        @if (form.patientStatus) {
          <fieldset class="form-group">
            <legend>狀態標記</legend>
            <div class="custom-checkbox-container">
              <div class="status-date-tag" [class.active]="form.patientStatus.isFirstDialysis?.active" (click)="toggleStatus('isFirstDialysis')">
                <span>首透</span>
                @if (form.patientStatus.isFirstDialysis?.active) {
                  <input type="date" [(ngModel)]="form.patientStatus.isFirstDialysis.date" name="firstDialysisStatusDate" (click)="$event.stopPropagation()" />
                }
              </div>
              <div class="status-date-tag" [class.active]="form.patientStatus.isPaused?.active" (click)="toggleStatus('isPaused')">
                <span>暫停透析</span>
                @if (form.patientStatus.isPaused?.active) {
                  <input type="date" [(ngModel)]="form.patientStatus.isPaused.date" name="pausedStatusDate" (click)="$event.stopPropagation()" />
                }
              </div>
              @if (patientType !== 'opd') {
                <div class="status-date-tag" [class.active]="form.patientStatus.hasBloodDraw?.active" (click)="toggleStatus('hasBloodDraw')">
                  <span>已抽血</span>
                  @if (form.patientStatus.hasBloodDraw?.active) {
                    <input type="date" [(ngModel)]="form.patientStatus.hasBloodDraw.date" name="bloodDrawStatusDate" (click)="$event.stopPropagation()" />
                  }
                </div>
              }
              <div class="status-date-tag do-not-move-tag" [class.active]="form.patientStatus.doNotMove?.active" (click)="toggleDoNotMove()">
                <span><i class="fas fa-lock"></i> 勿動</span>
                @if (form.patientStatus.doNotMove?.active) {
                  <input type="text" [(ngModel)]="form.patientStatus.doNotMove.reason" name="doNotMoveReason" placeholder="勿動原因…" (click)="$event.stopPropagation()" />
                }
              </div>
            </div>
          </fieldset>
        }
      </div>

      @if (isFirstPlanVisible) {
        <div class="first-plan-overlay" (click)="closeFirstDialysisPlan()">
          <div class="first-plan-dialog" (click)="$event.stopPropagation()">
            <div class="first-plan-header">
              <h3>首透連續洗設定</h3>
              <button type="button" class="close-button" (click)="closeFirstDialysisPlan()">&times;</button>
            </div>

            <div class="first-plan-controls">
              <label>
                開始日期
                <input type="date" [(ngModel)]="firstPlan.startDate" name="firstPlanStartDate" />
              </label>
              <label>
                連續天數
                <input type="number" min="1" max="6" [(ngModel)]="firstPlan.continuousDays" name="firstPlanDays" />
              </label>
              <label>
                常規頻率
                <select [(ngModel)]="firstPlan.regularFreq" name="firstPlanRegularFreq">
                  @for (f of FREQ_OPTIONS; track f) {
                    <option [value]="f">{{ f }}</option>
                  }
                </select>
              </label>
            </div>

            @if (firstPlanError) {
              <div class="plan-error">{{ firstPlanError }}</div>
            }

            <div class="first-plan-grid">
              <section class="plan-panel">
                <div class="panel-title">常規床位</div>
                <div class="selected-line">已選：{{ formatAssignment(firstPlan.regularAssignment) }}</div>
                <div class="bed-picker">
                  @for (shift of SHIFTS; track shift) {
                    <div class="shift-bed-group">
                      <h4>{{ SHIFT_LABELS[shift] }}</h4>
                      <div class="bed-chip-list">
                        @for (bed of regularAvailableBeds[shift]; track bed) {
                          <button
                            type="button"
                            class="bed-chip"
                            [class.selected]="firstPlan.regularAssignment?.bedNum === bed && firstPlan.regularAssignment?.shiftCode === shift"
                            [class.hepatitis-bed]="isHepatitisBed(bed)"
                            (click)="selectRegularBed(bed, shift)"
                          >
                            {{ formatBed(bed) }}
                          </button>
                        }
                      </div>
                    </div>
                  }
                </div>
              </section>

              <section class="plan-panel">
                <div class="panel-title">連續加洗</div>
                <div class="date-chip-list">
                  @for (item of continuousDates; track item.date) {
                    <button
                      type="button"
                      class="date-chip"
                      [class.selected]="firstPlan.selectedExtraDate === item.date"
                      [class.regular-day]="item.isRegular"
                      [class.disabled]="item.isRegular"
                      [class.has-extra]="hasExtraSession(item.date)"
                      (click)="selectExtraDate(item.date)"
                    >
                      <span>{{ item.weekdayLabel }}</span>
                      <small>{{ item.date }}</small>
                      @if (item.isRegular) {
                        <em>常規</em>
                      }
                      @if (hasExtraSession(item.date)) {
                        <i (click)="removeExtraSession(item.date, $event)">移除</i>
                      }
                    </button>
                  }
                </div>

                @if (firstPlan.selectedExtraDate) {
                  <div class="selected-line">
                    {{ firstPlan.selectedExtraDate }} 加洗床位：{{ formatAssignment(selectedExtraSession) }}
                  </div>
                  <div class="bed-picker compact">
                    @for (shift of SHIFTS; track shift) {
                      <div class="shift-bed-group">
                        <h4>{{ SHIFT_LABELS[shift] }}</h4>
                        <div class="bed-chip-list">
                          @for (bed of extraAvailableBeds[shift]; track bed) {
                            <button
                              type="button"
                              class="bed-chip"
                              [class.selected]="selectedExtraSession?.bedNum === bed && selectedExtraSession?.shiftCode === shift"
                              [class.hepatitis-bed]="isHepatitisBed(bed)"
                              (click)="selectExtraBed(bed, shift)"
                            >
                              {{ formatBed(bed) }}
                            </button>
                          }
                        </div>
                      </div>
                    }
                  </div>
                }
              </section>
            </div>

            <div class="first-plan-footer">
              @if (firstPlanLoading) {
                <span>載入床位中...</span>
              }
              <button type="button" class="btn-secondary" (click)="closeFirstDialysisPlan()">取消</button>
              <button type="button" class="btn-primary" (click)="applyFirstDialysisPlan()">套用設定</button>
            </div>
          </div>
        </div>
      }

      <div class="modal-footer">
        <button type="submit" class="btn-primary">儲存</button>
        <button type="button" class="btn-secondary" (click)="closeModal()">取消</button>
      </div>
    </form>
  </div>
</div>
